on:
  push:
    branches:
      - trunk
  workflow_dispatch:
  repository_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Configure S3
      uses: teahouse-hosting/configure-s3@trunk
      id: settings
      with:
        domain: example.teahouse.page
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
    - run: |
        aws s3 sync --delete . s3://${{steps.settings.outputs.bucket}}
